@MicroserviceB_HostAddress = http://localhost:5002

GET {{MicroserviceB_HostAddress}}/SayHello/say-hello
Accept: application/json

###

GET {{MicroserviceB_HostAddress}}/Count/count
Accept: application/json

###
