version: "3.8"

services:

  # --------------------------
  # Elasticsearch
  # --------------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  # --------------------------
  # Kibana
  # --------------------------
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  # --------------------------
  # Microservice A
  # --------------------------
  microservice-a:
    build:
      context: .
      dockerfile: MicroserviceA/Dockerfile   # Linux Dockerfile
    container_name: microservice-a
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch


  # --------------------------
  # Microservice B
  # --------------------------
  microservice-b:
    build:
      context: .
      dockerfile: MicroserviceB/Dockerfile   # Linux Dockerfile
    container_name: microservice-b
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch